AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Examplet to test checkov custom policy

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: not-a-real-bucket
      LoggingConfiguration:
        DestinationBucketName: !Sub 'logs-${AWS::AccountId}-${AWS::Region}'
        LogFilePrefix: !Sub 's3/${AWS::AccountId}/${AWS::Region}/not-a-real-bucket'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 3650
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
  BucketPolicy:
    # deny all non-ssl actions
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "s3:*"
              Effect: "Deny"
              Resource:
                - !GetAtt Bucket.Arn
                - !Join
                  - '/'
                  - - !GetAtt Bucket.Arn
                    - '*'
              Condition:
                Bool:
                  "aws:SecureTransport": false
              Principal: "*"